PhotoParallel/Web/Photoparallel.Web/Controllers/OrdersController.cs
namespace Photoparallel.Web.Controllers
{
    using System;
    using System.Collections.Generic;
    using System.Threading.Tasks;

    using AutoMapper;
    using Microsoft.AspNetCore.Authorization;
    using Microsoft.AspNetCore.Mvc;
    using Photoparallel.Data.Models.Enums;
    using Photoparallel.Services.Contracts;
    using Photoparallel.Web.Areas.Administration.ViewModels.Orders;
    using Photoparallel.Web.ViewModels.Orders;
    using X.PagedList;

    public class OrdersController : BaseController
    {
        private const int DefaultPageNumber = 1;
        private const int DefaultPageSize = 15;

        private readonly IOrdersService ordersService;
        private readonly IProductsService productsService;
        private readonly IMapper mapper;

        public OrdersController(IOrdersService ordersService, IProductsService productsService, IMapper mapper)
        {
            this.ordersService = ordersService;
            this.productsService = productsService;
            this.mapper = mapper;
        }

        [Authorize]
        public async Task<IActionResult> Index()
        {
            var orderViewModel = new OpenOrderViewModel();

            var openOrder = await this.ordersService.GetOpenOrderByUserIdAsync(this.User.Identity.Name);
            orderViewModel.Id = openOrder.Id;
            orderViewModel.TotalPrice = openOrder.TotalPrice;

            foreach (var product in openOrder.Products)
            {
                var orderProductViewModel = this.mapper.Map<OpenOrdersProductsViewModel>(product.Product);

                orderProductViewModel.OrderQuantity = product.Quantity;
                orderProductViewModel.TotalPrice = product.TotalPrice;

                orderViewModel.Products.Add(orderProductViewModel);
            }

            return this.View(orderViewModel);
        }

        [Authorize]
        public async Task<IActionResult> Add(int id)
        {
            var openOrder = await this.ordersService.GetOpenOrderByUserIdAsync(this.User.Identity.Name);

            await this.ordersService.AddProductAsync(id, openOrder);

            return this.RedirectToAction("Index");
        }

        [Authorize]
        public async Task<IActionResult> DeleteProduct(int id)
        {
            var order = await this.ordersService.GetOpenOrderByUserIdAsync(this.User.Identity.Name);

            await this.ordersService.DeleteProductAsync(id, order);

            return this.RedirectToAction("Index");
        }

        [Authorize]
        public async Task<IActionResult> Edit(int id, int quantity)
        {
            var order = await this.ordersService.GetOpenOrderByUserIdAsync(this.User.Identity.Name);

            await this.ordersService.EditProductQuantityAsync(id, quantity, order);

            return this.RedirectToAction("Index");
        }

        [Authorize]
        public async Task<IActionResult> Create()
        {
            var order = await this.ordersService.GetOpenOrderByUserIdAsync(this.User.Identity.Name);

            if (order == null || order.TotalPrice == 0)
            {
                return this.RedirectToAction("Index");
            }

            var createOrderInputModel = new CreateOrderInputModel
            {
                FirstName = order.Customer.FirstName,
                LastName = order.Customer.LastName,
                PhoneNumber = order.Customer.PhoneNumber,
                TotalPrice = order.TotalPrice,
            };

            return this.View(createOrderInputModel);
        }

        [Authorize]
        [HttpPost]
        public async Task<IActionResult> Create(CreateOrderInputModel model)
        {
            var order = await this.ordersService.GetOpenOrderByUserIdAsync(this.User.Identity.Name);

            model.TotalPrice = order.TotalPrice;

            if (!this.ModelState.IsValid)
            {
                return this.View(model);
            }

            string shippingAddress = model.City + ", " + model.PostalCode + Environment.NewLine + model.Address;

            await this.ordersService.SetOrderDetailsAsync(order, shippingAddress, model.FirstName, model.LastName, model.PhoneNumber, model.PaymentType);

            return this.RedirectToAction("Confirm");
        }

        [Authorize]
        public async Task<IActionResult> Confirm()
        {
            var order = await this.ordersService.GetOpenOrderByUserIdAsync(this.User.Identity.Name);

            if (order == null || order.TotalPrice == 0)
            {
                return this.RedirectToAction("Index");
            }

            var orderViewModel = this.mapper.Map<ConfirmOrderViewModel>(order);

            return this.View(orderViewModel);
        }

        [Authorize]
        public async Task<IActionResult> Finish()
        {
            var order = await this.ordersService.GetOpenOrderByUserIdAsync(this.User.Identity.Name);

            if (order == null || order.TotalPrice == 0)
            {
                return this.RedirectToAction("Index");
            }

            await this.ordersService.FinishOrderAsync(order);

            return this.View(order.Id);
        }

        [Authorize]
        public async Task<IActionResult> My(int? pageNumber, int? pageSize)
        {
            var orders = await this.ordersService.GetAllOrdersByUserAsync(this.User.Identity.Name);

            var allOrders = this.mapper.Map<IList<MyOrdersViewModel>>(orders);

            pageNumber = pageNumber ?? DefaultPageNumber;
            pageSize = pageSize ?? DefaultPageSize;
            var pageOrdersViewModel = allOrders.ToPagedList(pageNumber.Value, pageSize.Value);

            return this.View(pageOrdersViewModel);
        }

        [Authorize]
        public async Task<IActionResult> Details(int id)
        {
            var order = await this.ordersService.GetOrderByIdAsync(id);

            if (order == null || order.Customer.UserName != this.User.Identity.Name)
            {
                return this.View("OrderNotFound");
            }

            var orderProducts = await this.ordersService.OrderProductsByOrderIdAsync(id);
            var orderProductsViewModel = this.mapper.Map<IList<OrderProductsViewModel>>(orderProducts);

            var orderViewModel = this.mapper.Map<OrderDetailsViewModel>(order);
            orderViewModel.OrderProductsViewModel = orderProductsViewModel;

            if (order.OrderStatus == OrderStatus.Pending || order.OrderStatus == OrderStatus.Denied || order.OrderStatus == OrderStatus.WaitingCreditConfirmation)
            {
                orderViewModel.EstimatedDeliveryDate = "N/A";
                orderViewModel.Invoice = "N/A";
            }
            else
            {
                orderViewModel.EstimatedDeliveryDate = order.EstimatedDeliveryDate?.ToString(@"dd/MM/yyyy");
            }

            return this.View(orderViewModel);
        }
    }
}

PhotoParallel/Web/Photoparallel.Web/Controllers/ProductsController.cs
namespace Photoparallel.Web.Controllers
{
    using System.Threading.Tasks;

    using AutoMapper;
    using Microsoft.AspNetCore.Mvc;
    using Photoparallel.Common;
    using Photoparallel.Services.Contracts;
    using Photoparallel.Web.ViewModels.Products;

    public class ProductsController : BaseController
    {
        private readonly IProductsService productsService;
        private readonly IMapper mapper;

        public ProductsController(IProductsService productsService, IMapper mapper)
        {
            this.productsService = productsService;
            this.mapper = mapper;
        }

        public async Task<IActionResult> Details(int id)
        {
            var product = await this.productsService.GetProductByIdAsync(id);

            if (product == null)
            {
                return this.View("ProductNotFound");
            }

            if (!this.User.IsInRole(GlobalConstants.AdministratorRoleName) && product.Hide)
            {
                return this.View("ProductNotFound");            }

            var productViewModel = this.mapper.Map<DetailsProductViewModel>(product);

            return this.View(productViewModel);
        }
    }
}

PhotoParallel/Web/Photoparallel.Web/Controllers/RentsController.cs
namespace Photoparallel.Web.Controllers
{
    using System;
    using System.Collections.Generic;
    using System.Linq;
    using System.Threading.Tasks;

    using AutoMapper;
    using Microsoft.AspNetCore.Authorization;
    using Microsoft.AspNetCore.Mvc;
    using Photoparallel.Common;
    using Photoparallel.Data.Models.Enums;
    using Photoparallel.Services.Contracts;
    using Photoparallel.Web.Areas.Administration.ViewModels.Rents;
    using Photoparallel.Web.ViewModels.Home;
    using Photoparallel.Web.ViewModels.Rents;
    using X.PagedList;

    public class RentsController : BaseController
    {
        private const int DefaultPageNumber = 1;
        private const int DefaultPageSize = 8;
        private const int DefaultMyPageNumber = 1;
        private const int DefaultMyPageSize = 15;

        private readonly IProductsService productsService;
        private readonly IMapper mapper;
        private readonly IRentsService rentsService;

        public RentsController(IProductsService productsService, IMapper mapper, IRentsService rentsService)
        {
            this.productsService = productsService;
            this.mapper = mapper;
            this.rentsService = rentsService;
        }

        public async Task<IActionResult> Index(IndexViewModel model)
        {
            var products = await this.productsService.GetRentProductsAsync();
            products = this.productsService.OrderBy(products, model.SortBy).ToList();

            var productsViewModel = this.mapper.Map<IList<IndexProductViewModel>>(products);
            var allProductsViewModel = this.mapper.Map<IList<AllProductsVieModel>>(products);

            int pageNumber = model.PageNumber ?? DefaultPageNumber;
            int pageSize = model.PageSize ?? DefaultPageSize;
            var pageProductsViewMode = productsViewModel.ToPagedList(pageNumber, pageSize);

            model.ProductsViewModel = pageProductsViewMode;
            model.Products = allProductsViewModel;

            return this.View(model);
        }

        [Authorize]
        public async Task<IActionResult> Open()
        {
            var rentViewModel = new OpenRentViewModel();

            var openOrder = await this.rentsService.CreateOpenRentByUserIdAsync(this.User.Identity.Name);
            rentViewModel.Id = openOrder.Id;

            foreach (var product in openOrder.Products)
            {
                var rentProductViewModel = this.mapper.Map<OpenRentsProductsViewModel>(product.Product);

                rentProductViewModel.RentQuantity = product.Quantity;

                rentViewModel.Products.Add(rentProductViewModel);
            }

            rentViewModel.Guarantee = rentViewModel.Products.Sum(x => Math.Round(x.Price * GlobalConstants.GuaranteePercent));

            return this.View(rentViewModel);
        }

        [Authorize]
        public async Task<IActionResult> Add(int id)
        {
            var openRent = await this.rentsService.CreateOpenRentByUserIdAsync(this.User.Identity.Name);

            await this.rentsService.AddProductAsync(id, openRent);

            return this.RedirectToAction("Open");
        }

        [Authorize]
        public async Task<IActionResult> DeleteProduct(int id)
        {
            var rent = await this.rentsService.CreateOpenRentByUserIdAsync(this.User.Identity.Name);

            await this.rentsService.DeleteProductAsync(id, rent);

            return this.RedirectToAction("Open");
        }

        [Authorize]
        public async Task<IActionResult> Rent()
        {
            var rent = await this.rentsService.CreateOpenRentByUserIdAsync(this.User.Identity.Name);

            if (rent == null || rent.Products.Count() == 0)
            {
                return this.RedirectToAction("Open");
            }

            var rentProductInputModel = new RentProductInputModel()
            {
                FirstName = rent.Customer.FirstName,
                LastName = rent.Customer.LastName,
                PhoneNumber = rent.Customer.PhoneNumber,
            };

            return this.View(rentProductInputModel);
        }

        [Authorize]
        [HttpPost]
        public async Task<IActionResult> Rent(RentProductInputModel model)
        {
            var rent = await this.rentsService.CreateOpenRentByUserIdAsync(this.User.Identity.Name);

            if (!this.ModelState.IsValid)
            {
                return this.View(model);
            }

            rent.ShippingAddress = model.City + ", " + model.PostalCode + Environment.NewLine + model.Address;
            rent.Recipient = model.FirstName + " " + model.LastName;
            rent.RentDate = model.RentDate;
            rent.ReturnDate = model.ReturnDate.AddDays(1);
            rent.RecipientPhoneNumber = model.PhoneNumber;
            rent.Comment = model.Comment;
            rent.Guarantee = rent.Products.Sum(x => Math.Round(x.Product.Price * GlobalConstants.GuaranteePercent));

            await this.rentsService.SetRentDetailsAsync(rent);

            return this.RedirectToAction("Confirm");
        }

        [Authorize]
        public async Task<IActionResult> Confirm()
        {
            var rent = await this.rentsService.CreateOpenRentByUserIdAsync(this.User.Identity.Name);

            if (rent == null || rent.Products.Count() == 0)
            {
                return this.RedirectToAction("Index");
            }

            var days = rent.ReturnDate - rent.RentDate;

            rent.TotalPrice = rent.Products.Sum(x => x.Product.PricePerDay * (int)days.TotalDays);

            var rentViewModel = this.mapper.Map<ConfirmRentViewModel>(rent);

            return this.View(rentViewModel);
        }

        [Authorize]
        public async Task<IActionResult> Finish()
        {
            var rent = await this.rentsService.CreateOpenRentByUserIdAsync(this.User.Identity.Name);

            if (rent == null || rent.Products.Count() == 0)
            {
                return this.RedirectToAction("Index");
            }

            await this.rentsService.FinishRentAsync(rent);

            return this.View();
        }

        [Authorize]
        public async Task<IActionResult> My(int? pageNumber, int? pageSize)
        {
            var rents = await this.rentsService.GetAllRentsByUserAsync(this.User.Identity.Name);

            var rentsViewModel = this.mapper.Map<IList<MyRentsViewModel>>(rents);

            pageNumber = pageNumber ?? DefaultMyPageNumber;
            pageSize = pageSize ?? DefaultMyPageSize;
            var pageRentsViewModel = rentsViewModel.ToPagedList(pageNumber.Value, pageSize.Value);

            return this.View(pageRentsViewModel);
        }

        [Authorize]
        public async Task<IActionResult> Details(int id)
        {
            var rent = await this.rentsService.GetRentByIdAsync(id);

            if (rent == null || rent.Customer.UserName != this.User.Identity.Name)
            {
                return this.View("OrderNotFound");
            }

            var rentProducts = await this.rentsService.RentProductsByRentIdAsync(id);
            var rentProductsViewModel = this.mapper.Map<IList<RentProductsViewModel>>(rentProducts);

            var rentViewModel = this.mapper.Map<RentDetailsViewModel>(rent);
            rentViewModel.RentProductsViewModel = rentProductsViewModel;
            rentViewModel.PaymentStatus = "Paid";
            rentViewModel.Days = (int)(rent.ReturnDate - rent.RentDate).TotalDays;

            if (rent.RentStatus == RentStatus.Pending || rent.RentStatus == RentStatus.Denied || rent.RentStatus == RentStatus.Rented)
            {
                rentViewModel.Invoice = "N/A";
            }

            return this.View(rentViewModel);
        }
    }
}

PhotoParallel/Web/Photoparallel.Web/Views/Shared/Partials/_AdminPartial.cshtml
<li class="dropdown">
    <a href="#" class="dropdown-toggle" data-toggle="dropdown"><i class="fas fa-cog"></i> Products</a>
    <ul class="dropdown-menu dropdown-content bg-dark" role="menu">
        <li><a asp-area="Administration" asp-controller="Products" asp-action="All">All Products</a></li>
        <li><a asp-area="Administration" asp-controller="Products" asp-action="Rent">Rent Products</a></li>
        <li><a asp-area="Administration" asp-controller="Products" asp-action="Hidden">Hidden Products</a></li>
        <li><a asp-area="Administration" asp-controller="Products" asp-action="Oos">Out of Stock</a></li>
        <li><a asp-area="Administration" asp-controller="Products" asp-action="Create">Create Product</a></li>
    </ul>
</li>
<li class="dropdown">
    <a href="#" class="dropdown-toggle" data-toggle="dropdown"><i class="fas fa-cog"></i> Orders</a>
    <ul class="dropdown-menu dropdown-content bg-dark" role="menu">
        @*<li><a asp-area="Administration" asp-controller="Orders" asp-action="All">All</a></li>*@
        <li><a asp-area="Administration" asp-controller="Orders" asp-action="Pending">Pending</a></li>
        <li><a asp-area="Administration" asp-controller="Orders" asp-action="Waiting">Waiting</a></li>
        <li><a asp-area="Administration" asp-controller="Orders" asp-action="Approved">Approved</a></li>
        <li><a asp-area="Administration" asp-controller="Orders" asp-action="Shipped">Shipped</a></li>
        <li><a asp-area="Administration" asp-controller="Orders" asp-action="Delivered">Delivered</a></li>
        <li><a asp-area="Administration" asp-controller="Orders" asp-action="Denied">Denied</a></li>
    </ul>
</li>
<li class="dropdown">
    <a href="#" class="dropdown-toggle" data-toggle="dropdown"><i class="fas fa-cog"></i> Rents</a>
    <ul class="dropdown-menu dropdown-content bg-dark" role="menu">
        <li><a asp-area="Administration" asp-controller="Rents" asp-action="Pending">Pending</a></li>
        <li><a asp-area="Administration" asp-controller="Rents" asp-action="Rented">Rented</a></li>
        <li><a asp-area="Administration" asp-controller="Rents" asp-action="Returned">Returned</a></li>
        <li><a asp-area="Administration" asp-controller="Rents" asp-action="Denied">Denied</a></li>
    </ul>
</li>
<li class="dropdown">
    <a href="#" class="dropdown-toggle" data-toggle="dropdown"><i class="fas fa-cog"></i> Credits</a>
    <ul class="dropdown-menu dropdown-content bg-dark" role="menu">
        <li><a asp-area="Administration" asp-controller="Credits" asp-action="Pending">Pending</a></li>
        <li><a asp-area="Administration" asp-controller="Credits" asp-action="Approved">Approved</a></li>
        <li><a asp-area="Administration" asp-controller="Credits" asp-action="Denied">Denied</a></li>
        <li><a asp-area="Administration" asp-controller="CreditCompanies" asp-action="Create">Create Company</a></li>
        <li><a asp-area="Administration" asp-controller="CreditCompanies" asp-action="All">All Companies</a></li>
    </ul>
</li>
<ul class="nav navbar-nav navbar-left">
    <li><a asp-area="Administration" asp-controller="Invoices" asp-action="All"><i class="fas fa-cog"></i> Invoices</a></li>
</ul>

PhotoParallel/Web/Photoparallel.Web/Views/Shared/Partials/_FooterPartial.cshtml
<footer class="bg-dark m-4">
    <div class="container-fluid text-center text-md-left">
        <div class="row text-white">   
            <div class="col-md-4 mb-md-0 mb-3">
                <div class="m-3">
                    <a class="sticky-logo" href="/Home/Index">
                        <h1><span>Photo</span>Parallel</h1>
                    </a>
                </div>
                <div>
                    <ul class="text-left m-4">
                        <li class="m-2 text-muted"><i class="fas fa-phone"></i> +359 888 888 888</li>
                        <li class="m-2 text-muted"><i class="fas fa-envelope"></i> photoparallel@gmail.com</li>
                        <li class="m-2 text-muted"><i class="far fa-clock"></i> Working days: 09:30 - 18:30</li>
                    </ul>
                </div>
            </div>
            <div class="col-md-3 mb-md-0 mb-3">
                <h5 class="text-info text-left m-4">Products:</h5>
                <ul class="text-left m-4">                  
                    <li><a asp-area="" asp-controller="Home" asp-action="Camera" class="text-muted">Cameras</a></li>
                    <li><a asp-area="" asp-controller="Home" asp-action="Lens" class="text-muted">Lenses</a></li>
                    <li><a asp-area="" asp-controller="Home" asp-action="Drone" class="text-muted">Drones</a></li>
                    <li><a asp-area="" asp-controller="Home" asp-action="Microphone" class="text-muted">Microphones</a></li>
                    <li><a asp-area="" asp-controller="Home" asp-action="Stand" class="text-muted">Stands</a></li>
                    <li><a asp-area="" asp-controller="Home" asp-action="Bag" class="text-muted">Bags</a></li>
                    <li><a asp-area="" asp-controller="Home" asp-action="Accessory" class="text-muted">Accessories</a></li>                  
                </ul>
            </div>
            <div class="col-md-3 mb-md-0 mb-3">
                <h5 class="text-info text-left m-4">General:</h5>
                <ul class="text-left m-4">
                    <li><a class="text-muted" asp-area="" asp-controller="Home" asp-action="Contact">Contact</a></li>
                    <li class="mt-2"><a class="text-muted" asp-area="" asp-controller="Home" asp-action="Delivery">Delivery</a></li>
                    <li class="mt-2"><a class="text-muted" asp-area="" asp-controller="Home" asp-action="RentalTerms">Rental Terms</a></li>
                </ul>
            </div>
            <div class="col-md-2 mb-md-0 mb-3">
                <h5 class="text-info text-left m-4">Method of payment:</h5>
                <ul class="text-left m-4">
                    <li><span class="text-muted"><i class="fas fa-truck"></i> On delivery</span></li>
                    <li class="mt-2"><span class="text-muted"><i class="fab fa-cc-visa"></i> <i class="fab fa-cc-mastercard"></i> Bank transfer</span></li>
                    <li class="mt-2"><span class="text-muted"><i class="fas fa-file-invoice"></i> Credit</span></li>
                </ul>
                <div class="m-4">
                    <img src="~/img/visa-mastercard.png" width="90" alt="VisaMasterCard" />
                </div>               
            </div>
        </div>
    </div>
    <p class="text-center text-white">Copyright &copy; 2019 PhotoParallel. All rights reserved.</p>
</footer>

PhotoParallel/Web/Photoparallel.Web/Views/Shared/Partials/_LowerSectionPartial.cshtml
<nav class="navbar navbar-expand-lg navbar-dark bg-transparent">
    <div class="main-menu center-block">
        <ul class="nav navbar-nav">
            <li><a asp-area="" asp-controller="Home" asp-action="Index" class="text-info" ><i class="fas fa-home"></i> All</a></li>
            <li><a asp-area="" asp-controller="Home" asp-action="Camera" class="text-info" ><i class="fas fa-camera"></i> Cameras</a></li>
            <li><a asp-area="" asp-controller="Home" asp-action="Lens" class="text-info" ><i class="fa fa-camera-retro"></i> Lenses</a></li>
            <li><a asp-area="" asp-controller="Home" asp-action="Drone" class="text-info" ><i class="fas fa-helicopter"></i> Drones</a></li>
            <li><a asp-area="" asp-controller="Home" asp-action="Microphone" class="text-info"><i class="fas fa-microphone"></i> Microphones</a></li>
            <li><a asp-area="" asp-controller="Home" asp-action="Stand" class="text-info" ><i class="fab fa-stripe-s"></i> Stands</a></li>
            <li><a asp-area="" asp-controller="Home" asp-action="Bag" class="text-info" ><i class="fas fa-briefcase"></i> Bags</a></li>
            <li><a asp-area="" asp-controller="Home" asp-action="Accessory" class="text-info" ><i class="fab fa-adn"></i> Accessories</a></li>
            <li><a asp-area="" asp-controller="Rents" asp-action="Index" class="text-info" ><i class="fas fa-registered"></i> Rent</a></li>
        </ul>
    </div>
</nav>

PhotoParallel/Web/Photoparallel.Web/Views/Shared/Partials/_MiddleSectionPartial.cshtml
<div class="container col-md-12 col-sm-12">    
    <div class="d-flex justify-content-between">
        <div class="col-md-3 text-info font-italic fond-bold text-center" style="margin-top: 14px;">
            <i class="fas fa-phone"></i><strong> +359 888 888 888</strong>
        </div>
        <div class="col-md-6 center-block p-1">
            <form method="post" asp-area="" asp-controller="Home" asp-action="Index">
                <div class="input-group">                    
                    <input type="text" class="search-box mx-auto" id="Search" name="SearchString" placeholder="Search...">
                </div>
            </form>
        </div>
        <div class="col-md-3 text-info font-italic fond-bold text-center" style="margin-top: 14px;">
            <i class="fas fa-envelope"></i><strong> photoparallel@gmail.com</strong>
        </div>
    </div>
</div>

PhotoParallel/Web/Photoparallel.Web/Views/Shared/Partials/_UserPartial.cshtml
<li class="dropdown">
    <a class="dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
        <i class="fas fa-user-circle"></i> Hello, @this.User.Identity.Name!
    </a>
    <div class="dropdown-menu dropdown-content bg-dark" aria-labelledby="navbarDropdown">
        <a asp-area="" asp-controller="Orders" asp-action="My" class="dropdown-item nav-link text-white"><i class="fas fa-history"></i> My Orders</a>
        <a asp-area="" asp-controller="Rents" asp-action="My" class="dropdown-item nav-link text-white"><i class="fas fa-history"></i> My Rents</a>
        <a asp-area="" asp-controller="Invoices" asp-action="My" class="dropdown-item nav-link text-white"><i class="fas fa-history"></i> My Invoices</a>
        <a asp-area="" asp-controller="Credits" asp-action="My" class="dropdown-item nav-link text-white"><i class="fas fa-history"></i> My Credits</a>
        <a asp-area="Identity" asp-page="/Account/Manage/Index" class="dropdown-item nav-link text-white"><i class="fas fa-cog"></i> Settings</a>
        <a asp-area="Identity" asp-page="/Account/Logout" class="dropdown-item nav-link text-white"><i class="fas fa-sign-out-alt"></i> Exit</a>
    </div>
</li>
<li class="dropdown">
    @await Component.InvokeAsync(typeof(RentCartComponent))
</li>
<li class="dropdown">
    @await Component.InvokeAsync(typeof(ShoppingCartComponent))
</li>