PhotoParallel/Web/Photoparallel.Web/Areas/Administration/ViewModels/Orders/AllOrdersViewModel.cs
namespace Photoparallel.Web.Areas.Administration.ViewModels.Home
{
    using System;

    public class AllOrdersViewModel
    {
        public int Id { get; set; }

        public string OrderStatus { get; set; }

        public DateTime CreatedOn { get; set; }

        public DateTime? EstimatedDeliveryDate { get; set; }
    }
}

PhotoParallel/Web/Photoparallel.Web/Areas/Administration/Controllers/OrdersController.cs
namespace Photoparallel.Web.Areas.Administration.Controllers
{
    using System.Collections.Generic;
    using System.Threading.Tasks;

    using AutoMapper;
    using Microsoft.AspNetCore.Mvc;
    using Photoparallel.Data.Models.Enums;
    using Photoparallel.Services.Contracts;
    using Photoparallel.Web.Areas.Administration.ViewModels.Home;
    using Photoparallel.Web.Areas.Administration.ViewModels.Orders;
    using X.PagedList;

    public class OrdersController : AdministrationController
    {
        private const int DefaultPageNumber = 1;
        private const int DefaultPageSize = 15;

        private readonly IOrdersService ordersService;
        private readonly IMapper mapper;

        public OrdersController(IOrdersService ordersService, IMapper mapper)
        {
            this.ordersService = ordersService;
            this.mapper = mapper;
        }

        public async Task<IActionResult> All()
        {
            var orders = await this.ordersService.GetAllOrdersAsync();

            var allOrders = this.mapper.Map<IList<AllOrdersViewModel>>(orders);

            return this.View(allOrders);
        }

        public async Task<IActionResult> Pending()
        {
            var orders = await this.ordersService.GetPendingOrdersAsync();

            var allPendingOrders = this.mapper.Map<IList<AllOrdersViewModel>>(orders);

            return this.View(allPendingOrders);
        }

        public async Task<IActionResult> Waiting()
        {
            var orders = await this.ordersService.GetWaitingOrdersAsync();

            var waitingOrders = this.mapper.Map<IList<AllOrdersViewModel>>(orders);

            return this.View(waitingOrders);
        }

        public async Task<IActionResult> Approved()
        {
            var orders = await this.ordersService.GetApprovedOrdersAsync();

            var allApprovedOrders = this.mapper.Map<IList<AllOrdersViewModel>>(orders);

            return this.View(allApprovedOrders);
        }

        public async Task<IActionResult> Shipped()
        {
            var orders = await this.ordersService.GetShippedOrdersAsync();

            var allShippedOrders = this.mapper.Map<IList<AllOrdersViewModel>>(orders);

            return this.View(allShippedOrders);
        }

        public async Task<IActionResult> Delivered(int? pageNumber, int? pageSize)
        {
            var orders = await this.ordersService.GetDeliveredOrdersAsync();

            var allDeliveredOrders = this.mapper.Map<IList<AllOrdersViewModel>>(orders);

            pageNumber = pageNumber ?? DefaultPageNumber;
            pageSize = pageSize ?? DefaultPageSize;
            var pageOrdersViewModel = allDeliveredOrders.ToPagedList(pageNumber.Value, pageSize.Value);

            return this.View(pageOrdersViewModel);
        }

        public async Task<IActionResult> Denied(int? pageNumber, int? pageSize)
        {
            var orders = await this.ordersService.GetDeniedOrdersAsync();

            var allDeniedOrders = this.mapper.Map<IList<AllOrdersViewModel>>(orders);

            pageNumber = pageNumber ?? DefaultPageNumber;
            pageSize = pageSize ?? DefaultPageSize;
            var pageOrdersViewModel = allDeniedOrders.ToPagedList(pageNumber.Value, pageSize.Value);

            return this.View(pageOrdersViewModel);
        }

        public async Task<IActionResult> Details(int id)
        {
            var order = await this.ordersService.GetOrderByIdAsync(id);

            if (order == null)
            {
                return this.View("OrderNotFound");
            }

            var orderProducts = await this.ordersService.OrderProductsByOrderIdAsync(id);
            var orderProductsViewModel = this.mapper.Map<IList<OrderProductsViewModel>>(orderProducts);

            var orderViewModel = this.mapper.Map<OrderDetailsViewModel>(order);
            orderViewModel.OrderProductsViewModel = orderProductsViewModel;

            if (order.OrderStatus == OrderStatus.Pending || order.OrderStatus == OrderStatus.Denied || order.OrderStatus == OrderStatus.WaitingCreditConfirmation)
            {
                orderViewModel.EstimatedDeliveryDate = "N/A";
                orderViewModel.Invoice = "N/A";
            }
            else
            {
                orderViewModel.EstimatedDeliveryDate = order.EstimatedDeliveryDate?.ToString(@"dd/MM/yyyy");
            }

            return this.View(orderViewModel);
        }

        public async Task<IActionResult> Approve(int id)
        {
            await this.ordersService.ApproveAsync(id);

            return this.RedirectToAction("Pending");
        }

        public async Task<IActionResult> Ship(int id)
        {
            await this.ordersService.ShipAsync(id);

            return this.RedirectToAction("Approved");
        }

        public async Task<IActionResult> Deliver(int id)
        {
            await this.ordersService.DeliverAsync(id);

            return this.RedirectToAction("Shipped");
        }

        public async Task<IActionResult> Delete(int id)
        {
            var order = await this.ordersService.GetOrderByIdAsync(id);

            if (order == null)
            {
                return this.View("OrderNotFound");
            }

            var orderViewModel = this.mapper.Map<DeleteOrderViewModel>(order);

            return this.View(orderViewModel);
        }

        [HttpPost]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            await this.ordersService.DeleteOrderAsync(id);

            return this.RedirectToAction("Denied");
        }
    }
}

PhotoParallel/Web/Photoparallel.Web/Controllers/CreditsController.cs
namespace Photoparallel.Web.Controllers
{
    using System;
    using System.Collections.Generic;
    using System.Linq;
    using System.Security.Claims;
    using System.Threading.Tasks;

    using Microsoft.AspNetCore.Authorization;
    using Microsoft.AspNetCore.Mvc;
    using Photoparallel.Common;
    using Photoparallel.Data.Models.Enums;
    using Photoparallel.Services.Contracts;
    using Photoparallel.Web.ViewModels.Credits;
    using X.PagedList;

    public class CreditsController : BaseController
    {
        private const int DefaultPageNumber = 1;
        private const int DefaultPageSize = 15;

        private readonly ICreditsService creditsService;
        private readonly IOrdersService ordersService;
        private readonly ICreditCompaniesService creditCompaniesService;
        private readonly AutoMapper.IMapper mapper;

        public CreditsController(ICreditsService creditsService, IOrdersService ordersService, ICreditCompaniesService creditCompaniesService, AutoMapper.IMapper mapper)
        {
            this.creditsService = creditsService;
            this.ordersService = ordersService;
            this.creditCompaniesService = creditCompaniesService;
            this.mapper = mapper;
        }

        [Authorize]
        public async Task<IActionResult> AddProduct(int id)
        {
            var order = await this.ordersService.GetOpenOrderByUserIdAsync(this.User.Identity.Name);

            if (order == null)
            {
                return this.RedirectToAction("Index", "Orders");
            }

            await this.ordersService.AddProductAsync(id, order);

            return this.RedirectToAction("Create");
        }

        [Authorize]
        public async Task<IActionResult> Create()
        {
            var order = await this.ordersService.GetOpenOrderByUserIdAsync(this.User.Identity.Name);

            var creditCompanis = await this.creditCompaniesService.GetVisibleCompaniesAsync();

            if (order == null || order.TotalPrice < GlobalConstants.MinimumCreditValue)
            {
                return this.RedirectToAction("Index", "Orders");
            }

            if (creditCompanis.Count() == 0)
            {
                return this.View("NoCreditCompanies");
            }

            var creditViewModel = new CreateCreditInputModel()
            {
                FirstName = order.Customer.FirstName,
                LastName = order.Customer.LastName,
                PhoneNumber = order.Customer.PhoneNumber,
                Order = order,
                CreditCompanies = creditCompanis,
            };

            return this.View(creditViewModel);
        }

        [Authorize]
        [HttpPost]
        public async Task<IActionResult> Create(CreateCreditInputModel model)
        {
            var order = await this.ordersService.GetOpenOrderByUserIdAsync(this.User.Identity.Name);
            var creditCompanis = await this.creditCompaniesService.GetVisibleCompaniesAsync();
            var creditContract = await this.creditsService.GetOpenCreditsByUserIdAsync(this.User.FindFirst(ClaimTypes.NameIdentifier).Value);

            model.Order = order;
            model.CreditCompanies = creditCompanis;

            if (!this.ModelState.IsValid)
            {
                return this.View(model);
            }

            string address = model.City + ", " + model.PostalCode + Environment.NewLine + model.Address;
            string recipient = model.FirstName + " " + model.LastName;

            await this.ordersService.SetOrderDetailsAsync(order, address, model.FirstName, model.LastName, model.PhoneNumber, PaymentType.Credit);

            var creditCompany = creditCompanis.FirstOrDefault(x => x.Name == model.Company);

            await this.creditsService.SetCreditDetailsAsync(creditContract, order, address, creditCompany, model.Salary, model.Months, model.Ucn, model.IdNumber);

            return this.RedirectToAction("Confirm");
        }

        [Authorize]
        public async Task<IActionResult> Confirm()
        {
            var credit = await this.creditsService.GetOpenCreditsByUserIdAsync(this.User.FindFirst(ClaimTypes.NameIdentifier).Value);
            credit.Order = await this.ordersService.GetOpenOrderByUserIdAsync(this.User.Identity.Name);
            credit.CreditCompany = await this.creditCompaniesService.GetCompanyByIdAsync(credit.CreditCompanyId);

            if (credit == null || credit.TotalAmount == 0)
            {
                return this.RedirectToAction("Index", "Orders");
            }

            var creditViewModel = this.mapper.Map<ConfirmCreditViewModel>(credit);

            return this.View(creditViewModel);
        }

        [Authorize]
        public async Task<IActionResult> Finish()
        {
            var order = await this.ordersService.GetOpenOrderByUserIdAsync(this.User.Identity.Name);
            var credit = await this.creditsService.GetOpenCreditsByUserIdAsync(this.User.FindFirst(ClaimTypes.NameIdentifier).Value);

            if (order == null || order.TotalPrice == 0)
            {
                return this.RedirectToAction("Index", "Orders");
            }

            await this.ordersService.FinishOrderAsync(order);

            await this.creditsService.FinishCreditAsync(credit);

            return this.View();
        }

        [Authorize]
        public async Task<IActionResult> My(int? pageNumber, int? pageSize)
        {
            var credits = await this.creditsService.GetAllCreditsByUserAsync(this.User.Identity.Name);

            var allCredits = this.mapper.Map<IList<MyCreditssViewModel>>(credits);

            pageNumber = pageNumber ?? DefaultPageNumber;
            pageSize = pageSize ?? DefaultPageSize;
            var pageCreditsViewModel = allCredits.ToPagedList(pageNumber.Value, pageSize.Value);

            return this.View(pageCreditsViewModel);
        }

        [Authorize]
        public async Task<IActionResult> Details(int id)
        {
            var credit = await this.creditsService.GetCreditByIdAsync(id);

            if (credit == null || credit.Customer.UserName != this.User.Identity.Name)
            {
                return this.View("CreditNotFound");
            }

            var creditViewModel = this.mapper.Map<CreditDetailsViewModel>(credit);

            return this.View(creditViewModel);
        }
    }
}

PhotoParallel/Web/Photoparallel.Web/Controllers/InvoicesController.cs
namespace Photoparallel.Web.Controllers
{
    using System.Collections.Generic;
    using System.Linq;
    using System.Security.Claims;
    using System.Threading.Tasks;

    using AutoMapper;
    using Microsoft.AspNetCore.Authorization;
    using Microsoft.AspNetCore.Mvc;
    using Photoparallel.Services.Contracts;
    using Photoparallel.Web.ViewModels.Invoices;
    using X.PagedList;

    public class InvoicesController : BaseController
    {
        private const int DefaultPageNumber = 1;
        private const int DefaultPageSize = 15;

        private readonly IInvoicesService invoicesService;
        private readonly IOrdersService ordersService;
        private readonly IMapper mapper;
        private readonly IRentsService rentsService;

        public InvoicesController(IInvoicesService invoicesService, IOrdersService ordersService, IMapper mapper, IRentsService rentsService)
        {
            this.invoicesService = invoicesService;
            this.ordersService = ordersService;
            this.mapper = mapper;
            this.rentsService = rentsService;
        }

        [Authorize]
        public async Task<IActionResult> Details(int id)
        {
            var invoice = await this.invoicesService.GetInvoiceByIdAsync(id);

            if (invoice == null || invoice.Customer.UserName != this.User.Identity.Name)
            {
                return this.View("InvoiceNotFound");
            }

            if (invoice.Order == null)
            {
                return this.RedirectToAction("RentDetails", new { id = invoice.Id });
            }

            var orderProducts = await this.ordersService.OrderProductsByOrderIdAsync(invoice.Order.Id);
            var invoiceProductsViewModel = this.mapper.Map<IList<InvoiceOrderProductsViewModel>>(orderProducts);

            var invoiceViewModel = this.mapper.Map<InvoiceViewModel>(invoice);
            invoiceViewModel.InvoiceProducts = invoiceProductsViewModel;

            return this.View(invoiceViewModel);
        }

        [Authorize]
        public async Task<IActionResult> RentDetails(int id)
        {
            var invoice = await this.invoicesService.GetInvoiceByIdAsync(id);

            if (invoice == null || invoice.Customer.UserName != this.User.Identity.Name)
            {
                return this.View("InvoiceNotFound");
            }

            if (invoice.Rent == null)
            {
                return this.RedirectToAction("Details", new { id = invoice.Id });
            }

            var rentProducts = await this.rentsService.RentProductsByRentIdAsync(invoice.Rent.Id);
            var invoiceProductsViewModel = this.mapper.Map<IList<InvoiceRentProductsViewModel>>(rentProducts);

            var rentProduct = rentProducts.FirstOrDefault();
            var days = (int)(rentProduct.Rent.ReturnDate - rentProduct.Rent.RentDate).TotalDays;

            var invoiceViewModel = this.mapper.Map<InvoiceRentViewModel>(invoice);
            invoiceViewModel.Days = days;
            invoiceViewModel.InvoiceProducts = invoiceProductsViewModel;

            return this.View(invoiceViewModel);
        }

        [Authorize]
        public async Task<IActionResult> My(int? pageNumber, int? pageSize)
        {
            var allInvoices = await this.invoicesService.GetAllAsync();

            var allMyInvoices = allInvoices.Where(x => x.CustomerId == this.User.FindFirst(ClaimTypes.NameIdentifier).Value)
                .OrderByDescending(x => x.IssuedOn);

            var allMyInvoicesViewModel = this.mapper.Map<IList<MyInvoicesViewModel>>(allMyInvoices);

            pageNumber = pageNumber ?? DefaultPageNumber;
            pageSize = pageSize ?? DefaultPageSize;
            var pageInvoicesViewModel = allMyInvoicesViewModel.ToPagedList(pageNumber.Value, pageSize.Value);

            return this.View(pageInvoicesViewModel);
        }
    }
}

PhotoParallel/Web/Photoparallel.Web/Controllers/ProductsController.cs
namespace Photoparallel.Web.Controllers
{
    using System.Threading.Tasks;

    using AutoMapper;
    using Microsoft.AspNetCore.Mvc;
    using Photoparallel.Common;
    using Photoparallel.Services.Contracts;
    using Photoparallel.Web.ViewModels.Products;

    public class ProductsController : BaseController
    {
        private readonly IProductsService productsService;
        private readonly IMapper mapper;

        public ProductsController(IProductsService productsService, IMapper mapper)
        {
            this.productsService = productsService;
            this.mapper = mapper;
        }

        public async Task<IActionResult> Details(int id)
        {
            var product = await this.productsService.GetProductByIdAsync(id);

            if (product == null)
            {
                return this.View("ProductNotFound");
            }

            if (!this.User.IsInRole(GlobalConstants.AdministratorRoleName) && product.Hide)
            {
                return this.View("ProductNotFound");            }

            var productViewModel = this.mapper.Map<DetailsProductViewModel>(product);

            return this.View(productViewModel);
        }
    }
}

PhotoParallel/Web/Photoparallel.Web/Views/Orders/Confirm.cshtml
@model Photoparallel.Web.ViewModels.Orders.ConfirmOrderViewModel

@{
    ViewData["Title"] = "Confirm";
}

<div class="progress pt-1">
    <div class="progress-bar" role="progressbar" style="width: 100%;" aria-valuenow="100" aria-valuemin="0" aria-valuemax="100">100%</div>
</div>

<div class="row">
    <div class="col-md-6">
        <div class="card card-body bg-info">
            <div><span class="font-weight-bold">Recipient:</span> @Model.Recipient</div>
            <hr />
            <div><span class="font-weight-bold">Phone Number:</span> @Model.RecipientPhoneNumber</div>
            <hr />
            <div><span class="font-weight-bold">Address:</span> @Model.ShippingAddress</div>
            <hr />
            <div><span class="font-weight-bold">Payment Method:</span> @Model.PaymentType</div>
        </div>
        <div class="container-fluid d-flex justify-content-around m-5">
            <div class="mb-2">
                <a asp-controller="Orders" asp-action="Create" asp-route-id="@Model.Id" asp-route-direct="true" class="myButton-orange btn-lg btn-block text-center"><i class="fas fa-cog"></i> Edit</a>
            </div>
            @if (Model.PaymentType == "Visa/MasterCard")
            {
                <div class="mb-2">
                    <a asp-controller="CreditCards" asp-action="Pay" asp-route-id="@Model.Id" asp-route-direct="true" class="myButton-olive btn-lg btn-block text-center"><i class="far fa-credit-card"></i> Pay</a>
                </div>
            }
            else
            {
                <div class="mb-2">
                    <a asp-controller="Orders" asp-action="Finish" asp-route-id="@Model.Id" asp-route-direct="true" class="myButton-olive btn-lg btn-block text-center"><i class="fas fa-check"></i> Finish</a>
                </div>
            }
        </div>
    </div>
    <div class="col-md-6">
        <div class="container-fluid">
            @await Component.InvokeAsync(typeof(OpenOrderComponent), new { OrderId = Model.Id })
            @if (Model.TotalPrice < GlobalConstants.FreeShippingLimitAmount)
            {
                <div class="text-center">
                    <p class="font-weight-bold text-danger h4 text-right">Shipping: @Model.ShippingCosts BGN</p>
                </div>
                <hr />
                <div class="text-center">
                    <p class="font-weight-bold text-danger h3 text-right">Grand Total: @(Model.TotalPrice + Model.ShippingCosts) BGN</p>
                </div>
            }
            else
            {
                <div class="text-center">
                    <p class="font-weight-bold text-danger h4 text-right">Free Shipping</p>
                </div>
                <hr />
                <div class="text-center">
                    <p class="font-weight-bold text-danger h3 text-right">Grand Total: @(Model.TotalPrice) BGN</p>
                </div>
            }
        </div>
    </div>
</div>

PhotoParallel/Web/Photoparallel.Web/Views/Orders/Details.cshtml
@model Photoparallel.Web.Areas.Administration.ViewModels.Orders.OrderDetailsViewModel

@{
    ViewData["Title"] = "Details";
}

<div class="h2 text-center text-info font-weight-bold">Order Details</div>
<hr class="w-50" />
<div class="col-md-6">
    <div class="h4 font-weight-bold text-center text-info">Order Details:</div>
    <div class="card card-body bg-transparent shadow">
        <div><span class="font-weight-bold">Order №:</span> @Model.Id</div>
        <div><span class="font-weight-bold">Created On:</span> @Model.CreatedOn</div>
        <div><span class="font-weight-bold">Order Status:</span> @Model.OrderStatus</div>
        <div><span class="font-weight-bold">Payment Status:</span> @Model.PaymentStatus</div>
        @if (Model.OrderStatus == "Delivered")
        {
            <div><span class="font-weight-bold">Delivered On:</span> @Model.EstimatedDeliveryDate</div>
        }
        else
        {
            <div><span class="font-weight-bold">Estimated Delivery Date:</span> @Model.EstimatedDeliveryDate</div>
        }
        @if (Model.Invoice != "N/A")
        {
            <div>
                <span class="font-weight-bold">Invoice №:</span>
                <a asp-area="" asp-controller="Invoices" asp-action="Details" asp-route-id="@Model.InvoiceId">
                    <u>@Model.Invoice</u>
                </a>
            </div>
        }
        else
        {
            <div><span class="font-weight-bold">Invoice №:</span> @Model.Invoice</div>
        }
        @if (Model.CreditContract != null)
        {
            <div>
                <span class="font-weight-bold">Credit Contract №:</span>
                <a asp-area="" asp-controller="Credits" asp-action="Details" asp-route-id="@Model.CreditContract.Id">
                    <u>@Model.CreditContract.Id</u>
                </a>
            </div>
        }
        <div><span class="font-weight-bold">All Products:</span> @Model.TotalPrice BGN</div>
        <div><span class="font-weight-bold">Shipping:</span> @Model.Shipping BGN</div>
        <hr />
        <div class="h4"><span class="font-weight-bold">Grand Total:</span> @Model.GrandTotal BGN</div>
    </div>
</div>
<div class="col-md-6">
    <div class="h4 font-weight-bold text-center text-info">Recipent Data:</div>
    <div class="card card-body bg-transparent shadow">
        <div><span class="font-weight-bold">Recipient:</span> @Model.Recipient</div>
        <hr />
        <div><span class="font-weight-bold">Phone Number:</span> @Model.RecipientPhoneNumber</div>
        <hr />
        <div><span class="font-weight-bold">Address:</span> @Model.ShippingAddress</div>
    </div>
</div>
<table class="table">
    <thead>
        <tr class="row d-flex justify-content-around">
            <th scope="col" class="col-md-2 col d-flex justify-content-center"></th>
            <th scope="col" class="col-md-1 col d-flex justify-content-center">Product №</th>
            <th scope="col" class="col-md-4 col d-flex justify-content-center">Name</th>
            <th scope="col" class="col-md-2 col d-flex justify-content-center">Price</th>
            <th scope="col" class="col-md-1 col d-flex justify-content-center">Quantity</th>
            <th scope="col" class="col-md-2 col d-flex justify-content-center">Total Price</th>
        </tr>
    </thead>
    <tbody>
        @foreach (var product in Model.OrderProductsViewModel)
        {
            <tr class="row d-flex justify-content-around">
                <td class="col-md-2 col d-flex justify-content-center">
                    <img src="@product.ImageUrl" width="50" height="50">
                </td>
                <td class="col-md-1 col d-flex justify-content-center">
                    @product.ProductId
                </td>
                <td class="col-md-4 col d-flex justify-content-center">
                    @product.ProductName
                </td>
                <td class="col-md-2 col d-flex justify-content-center">
                    @product.Price BGN
                </td>
                <td class="col-md-1 col d-flex justify-content-center">
                    @product.Quantity
                </td>
                <td class="col-md-2 col d-flex justify-content-center">
                    @(product.Price * product.Quantity) BGN
                </td>
            </tr>
        }
    </tbody>
</table>

PhotoParallel/Web/Photoparallel.Web/Views/Orders/Finish.cshtml
@{
    ViewData["Title"] = "Finish";
}

<h1 class="text-center text-info">Thank You for Your Order!</h1>

PhotoParallel/Web/Photoparallel.Web/Views/Orders/Index.cshtml
@model Photoparallel.Web.ViewModels.Orders.OpenOrderViewModel

@{
    ViewData["Title"] = "Shopping Cart";
}

@if (Model.Products.Count == 0)
{
    <div class="progress pt-1">
        <div class="progress-bar" role="progressbar" style="width: 0%;" aria-valuenow="0" aria-valuemin="0" aria-valuemax="100">0%</div>
    </div>
}
else
{
    <div class="progress pt-1">
        <div class="progress-bar" role="progressbar" style="width: 33%;" aria-valuenow="33" aria-valuemin="0" aria-valuemax="100">33%</div>
    </div>
}

<div class="mobile-fondsize-20 h2 text-info text-center">@ViewData["Title"]</div>
<hr class="w-50" />
@if (Model.Products.Count() == 0)
{
    <h3 class="text-center">Your shopping cart is empty.</h3>
    <hr class="w-50" />

    <div class="d-flex justify-content-around m-5">
        <div class="text-center mt-3 mb-3 w-40">
            <a asp-controller="Home" asp-action="Index" class="form-group myButton-blue btn-lg btn-block mb-0">Start Shopping</a>
        </div>
    </div>
}
else
{
    <div class="row">
        <div class="col-lg-8">
            <div class="container mobile-fondsize-11">
                <table class="table">
                    <thead>
                        <tr class="row">
                            <th scope="col" class="col-2 d-flex justify-content-center">Product</th>
                            <th scope="col" class="col-4 d-flex justify-content-center"></th>
                            <th scope="col" class="col-2 d-flex justify-content-center">Price</th>
                            <th scope="col" class="col-1 d-flex justify-content-center">Quantity</th>
                            <th scope="col" class="col-2 d-flex justify-content-center">Total</th>
                            <th scope="col" class="col-1 d-flex justify-content-center"></th>
                        </tr>
                    </thead>
                    <tbody>
                        @foreach (var product in Model.Products)
                        {
                            <tr class="row">
                                <td class="col-2 d-flex justify-content-center">
                                    <a asp-area="" asp-controller="Products" asp-action="Details" asp-route-id="@product.Id">
                                        <img src="@product.ImageUrl" width="50" height="50">
                                    </a>
                                </td>
                                <td class="col-4 d-flex justify-content-center">
                                    <a asp-area="" asp-controller="Products" asp-action="Details" asp-route-id="@product.Id">
                                        @product.Name
                                    </a>
                                </td>
                                <td class="col-2 d-flex justify-content-center">@product.Price</td>
                                <td class="col-1 d-flex justify-content-center">
                                    <a class="text-danger pr-2" asp-controller="Orders" asp-action="Edit" asp-route-id="@product.Id" asp-route-quantity="@(product.OrderQuantity - 1)"><i class="fas fa-minus-circle"> </i> </a>
                                    @product.OrderQuantity
                                    <a class="text-danger pl-2" asp-controller="Orders" asp-action="Edit" asp-route-id="@product.Id" asp-route-quantity="@(product.OrderQuantity + 1)"><i class="fas fa-plus-circle"> </i> </a>
                                </td>
                                <td class="col-2 d-flex justify-content-center">@product.TotalPrice</td>
                                <td class="col-1 d-flex justify-content-center">
                                    <a class="text-danger" asp-controller="Orders" asp-action="DeleteProduct" asp-route-id="@product.Id"><i class="fa fa-trash"></i></a>
                                </td>
                            </tr>
                        }
                    </tbody>
                </table>
            </div>
        </div>
    </div>
    <div class="row">
        <div class="col-md-8">
            <div class="mt-4">
                <p class="font-weight-bold text-danger h4 mt-3">Total amount: @(Model.TotalPrice) BGN</p>
            </div>
        </div>
        <div class="col-md-4 d-flex justify-content-around">
            <div class="text-right mt-3 mb-3">
                <a asp-controller="Home" asp-action="Index" class="form-group myButton-blue btn-sm btn-block mb-0">Add Product</a>
            </div>
            <div class="text-right mt-3 mb-3">
                <a asp-controller="Orders" asp-action="Create" class="form-group myButton-olive btn-sm btn-block mb-0">Finish Order</a>
            </div>
            @if (Model.TotalPrice >= GlobalConstants.MinimumCreditValue)
            {
                <div class="text-right mt-3 mb-3">
                    <a asp-controller="Credits" asp-action="Create" class="form-group myButton-red btn-sm btn-block mb-0">Buy on Credit</a>
                </div>
            }
        </div>
    </div>
}